//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFPlusPlusBiggy.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyEntities : DbContext
    {
        public MyEntities()
            : base("name=MyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bzFDT> bzFDTs { get; set; }
        public virtual DbSet<bzSOD> bzSODs { get; set; }
    
        public virtual ObjectResult<GetbzSOD_Result> GetbzSOD(Nullable<int> salesOrderDetailId)
        {
            var salesOrderDetailIdParameter = salesOrderDetailId.HasValue ?
                new ObjectParameter("SalesOrderDetailId", salesOrderDetailId) :
                new ObjectParameter("SalesOrderDetailId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetbzSOD_Result>("GetbzSOD", salesOrderDetailIdParameter);
        }
    }
}
